//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.20 at 11:44:23 AM IST 
//


package org.jainy.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Root_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Root_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}TestOrgInfo" minOccurs="0"/>
 *         &lt;element ref="{}OrgInfo" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Root_Type", propOrder = {
    "testOrgInfo",
    "orgInfo"
})
public class RootType {

    @XmlElement(name = "TestOrgInfo")
    protected TestOrgInfoType testOrgInfo;
    @XmlElement(name = "OrgInfo")
    protected OrgInfoType orgInfo;

    /**
     * Gets the value of the testOrgInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TestOrgInfoType }
     *     
     */
    public TestOrgInfoType getTestOrgInfo() {
        return testOrgInfo;
    }

    /**
     * Sets the value of the testOrgInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestOrgInfoType }
     *     
     */
    public void setTestOrgInfo(TestOrgInfoType value) {
        this.testOrgInfo = value;
    }

    /**
     * Gets the value of the orgInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OrgInfoType }
     *     
     */
    public OrgInfoType getOrgInfo() {
        return orgInfo;
    }

    /**
     * Sets the value of the orgInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgInfoType }
     *     
     */
    public void setOrgInfo(OrgInfoType value) {
        this.orgInfo = value;
    }

}
