//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.20 at 11:44:23 AM IST 
//


package org.jainy.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestAddress_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestAddress_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TestAddr1" minOccurs="0"/>
 *         &lt;element ref="{}TestAddr2" minOccurs="0"/>
 *         &lt;element ref="{}TestAddr3" minOccurs="0"/>
 *         &lt;element ref="{}TestAddr4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestAddress_Type", propOrder = {
    "testAddr1",
    "testAddr2",
    "testAddr3",
    "testAddr4"
})
public class TestAddressType {

    @XmlElement(name = "TestAddr1")
    protected String testAddr1;
    @XmlElement(name = "TestAddr2")
    protected String testAddr2;
    @XmlElement(name = "TestAddr3")
    protected String testAddr3;
    @XmlElement(name = "TestAddr4")
    protected String testAddr4;

    /**
     * Gets the value of the testAddr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestAddr1() {
        return testAddr1;
    }

    /**
     * Sets the value of the testAddr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestAddr1(String value) {
        this.testAddr1 = value;
    }

    /**
     * Gets the value of the testAddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestAddr2() {
        return testAddr2;
    }

    /**
     * Sets the value of the testAddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestAddr2(String value) {
        this.testAddr2 = value;
    }

    /**
     * Gets the value of the testAddr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestAddr3() {
        return testAddr3;
    }

    /**
     * Sets the value of the testAddr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestAddr3(String value) {
        this.testAddr3 = value;
    }

    /**
     * Gets the value of the testAddr4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestAddr4() {
        return testAddr4;
    }

    /**
     * Sets the value of the testAddr4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestAddr4(String value) {
        this.testAddr4 = value;
    }

}
