//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.20 at 11:44:23 AM IST 
//


package org.jainy.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestOrgInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestOrgInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TestCompositeContactInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Dummy"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestOrgInfo_Type", propOrder = {
    "testCompositeContactInfo",
    "dummy"
})
public class TestOrgInfoType {

    @XmlElement(name = "TestCompositeContactInfo")
    protected List<TestCompositeContactInfoType> testCompositeContactInfo;
    @XmlElement(name = "Dummy", required = true)
    protected DummyType dummy;

    /**
     * Gets the value of the testCompositeContactInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCompositeContactInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCompositeContactInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestCompositeContactInfoType }
     * 
     * 
     */
    public List<TestCompositeContactInfoType> getTestCompositeContactInfo() {
        if (testCompositeContactInfo == null) {
            testCompositeContactInfo = new ArrayList<TestCompositeContactInfoType>();
        }
        return this.testCompositeContactInfo;
    }

    /**
     * Gets the value of the dummy property.
     * 
     * @return
     *     possible object is
     *     {@link DummyType }
     *     
     */
    public DummyType getDummy() {
        return dummy;
    }

    /**
     * Sets the value of the dummy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DummyType }
     *     
     */
    public void setDummy(DummyType value) {
        this.dummy = value;
    }

}
