//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.20 at 11:44:23 AM IST 
//


package org.jainy.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestCompositeContactInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestCompositeContactInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ContactInfo"/>
 *         &lt;element ref="{}TestAddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestCompositeContactInfo_Type", propOrder = {
    "contactInfo",
    "testAddress"
})
public class TestCompositeContactInfoType {

    @XmlElement(name = "ContactInfo", required = true)
    protected ContactInfoType contactInfo;
    @XmlElement(name = "TestAddress", required = true)
    protected TestAddressType testAddress;

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType }
     *     
     */
    public ContactInfoType getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType }
     *     
     */
    public void setContactInfo(ContactInfoType value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the testAddress property.
     * 
     * @return
     *     possible object is
     *     {@link TestAddressType }
     *     
     */
    public TestAddressType getTestAddress() {
        return testAddress;
    }

    /**
     * Sets the value of the testAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestAddressType }
     *     
     */
    public void setTestAddress(TestAddressType value) {
        this.testAddress = value;
    }

}
